### ISSUE TITLE
Make it available in English and in Java

### ISSUE THREAD

**Issue by NarzaryU** [smartlook/android-consent-sdk#1]
Please make it in java

**Comment by SenNeonoveNoci** [comment]
Hi @NehemiahNarzary,

I'm afraid we currently don't have any plans on rewriting this to Java. But why is Kotlin a problem for you?
Also, what do you mean with "Make it available in English"?

**Comment by NarzaryU** [comment]
Hello @SenNeonoveNoci 
 
I'm new to coding and just know a single language, that is java. My project is in Java and I've been searching for days how to take user consent before they use my app. At last I saw your article on your website today and was happy about it. Soon my happiness turned to sadness on seeing the language used here in Kotlin. 

What I meant by change the language into English is that the language in the screenshot is other than English.

It would be helpful if you suggest me how to use your library in my Java project. That would be helpful for me.

**Comment by pavel-kroh-smartlook** [comment]
Hi @NehemiahNarzary , the language in the screenshots is a placeholder pseudo-latin text, known as "Lore Ipsum" (https://en.wikipedia.org/wiki/Lorem_ipsum). To use this library in your app, you have to replace it in your own text, that will reflect what your app does and requests from your users.

**Comment by SenNeonoveNoci** [comment]
Hi @NehemiahNarzary,

you can use this library in Java project with no problem. Kotlin and Java are interoperable. Just the sample codes are in Kotlin, but I'm sure you will be able to understand them and write similar code in Java. 

Also, Kotlin is an amazing language that you can use to develop Android make sure you take a look at it. You will not regret it!

**Comment by NarzaryU** [comment]
Thank you for your response.
